# Ensures the pull request title matches Conventional Commits.
# Borrowed from the symend-react repo. See https://github.com/symend/symend-react/blob/main/.github/workflows/lint-pr.yml

name: All | Validate PR Titles to Meet Conventional Commits
on:
  pull_request:
    branches:
      - 'main'
    types: [opened, edited, reopened]

concurrency:
  group: lint-pr-title-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: Lint Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^.*(?:[Bb]ump|\s*\[[A-Z]{2,10}-[0-9]+\]) .+$
          wip: true
          validateSingleCommit: true