# Use a github workflow with the package from https://github.com/actions/labeler to automatically label PRs

name: All | Label Pull Requests

on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/all-pr-labeler/all-pr-labeler-config.yml