# Executes sqlfluff to lint all sql files 

name: All | Snowflake | SQLFluff Linter

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**/all-snowflake-sqlfluff-linter.yml' # For testing, only run on push when this file is modified.
  pull_request:
    paths:
      - '.github/**/all-snowflake-sqlfluff-linter.yml' # this file
      - */**.sql # all sql files

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-code:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install SQLFluff
        run: python -m pip install sqlfluff
      
      - name: Get Files Changed in the Push or PR
        id: get-pr-changes
        uses: tj-actions/changed-files@v35.6.3
        with:
          files: */**.sql

      - name: List changed files
        run: echo ${{ steps.get-pr-changes.outputs.all_changed_files }}
      
      - name: Lint Changed Files
        if: steps.get-pr-changes.outputs.all_changed_files != ''
        run: sqlfluff lint --format github-annotation --annotation-level failure --nofail ${{ steps.get-pr-changes.outputs.all_changed_files }} > annotations.json

      - name: Annotate PR
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "SQLFluff Lint"
          input: "./annotations.json"