name: Prefix PR title and update description with JIRA number

# Specify permissions
permissions:
  pull-requests: write  # Ensure the action has permission to modify PRs

on:
  pull_request:
    types: [opened]

jobs:
  update_pr_title_and_description:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch_name::${{ github.head_ref }}"

      - name: Extract JIRA number from branch
        id: extract_jira
        run: |
          # Modify this regex based on your JIRA ticket pattern (e.g., ABC-123)
          branch_name="${{ steps.extract_branch.outputs.branch_name }}"
          jira_number=$(echo "$branch_name" | grep -oE '[a-z]+-[0-9]+')

          if [ -z "$jira_number" ]; then
            echo "No JIRA number found in branch name"
            exit 1
          fi

          echo "::set-output name=jira_number::$jira_number"

      - name: Update PR title and description with JIRA number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jira_number="${{ steps.extract_jira.outputs.jira_number }}"
          current_title="${{ github.event.pull_request.title }}"
          current_body="${{ github.event.pull_request.body }}"

          # Prefix the PR title with the JIRA number
          new_title="$jira_number: $current_title"

          # Check if the "Related issues" section exists in the body
          if [[ "$current_body" == *"## :bulb: Related issues"* ]]; then
            # If the section exists, append the JIRA number to it
            new_body=$(echo "$current_body" | sed "s|## :bulb: Related issues|## :bulb: Related issues\n\n- $jira_number|")
          else
            # If the section doesn't exist, create it and add the JIRA number
            new_body="$current_body\n\n## :bulb: Related issues\n\n- $jira_number"
          fi

          # Escape newlines and special characters in title and body for JSON compatibility
          escaped_title=$(echo "$new_title" | jq -R .)
          escaped_body=$(echo "$new_body" | jq -R .)

          # Update the PR title and body via GitHub API
          pr_number="${{ github.event.pull_request.number }}"
          repo="${{ github.repository }}"

          curl -s -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$repo/pulls/$pr_number \
            -d "{\"title\":$escaped_title, \"body\":$escaped_body}"
