name: Prepend Branch Info to PR Title

on:
  pull_request:
    types: [opened]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Enforce Jira Issue Key in Pull Request Title
      uses: ryanvade/enforce-pr-title-style-action@v2.1.2
      with:
        projectKeys: |
            'kirk'
            'pl'
            'chore'
