name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install pytest

      - name: Run tests and save output
        run: |
          mkdir -p test-results
          pytest -v | tee test-results/output.log
          tail -n 10 test-results/output.log > test-summary.txt

      - name: Add test summary to GitHub UI
        run: |
          echo "### 🧪 Test Summary" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat test-summary.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload full test log
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: test-results/output.log
