name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests and save output
        run: |
          mkdir -p test-results
          pytest -v | tee test-results/output.log
          tail -n 10 test-results/output.log > test-summary.txt

      - name: Post test summary as comment on PR
        if: github.event.pull_request.head.repo.full_name == github.repository  # Only for PRs from the same repository
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('test-summary.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧪 **Test Summary**\n\`\`\`\n${summary}\n\`\`\``
            });

      - name: Upload full test log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: test-results/output.log
