name: Run Tests and Post Results

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code from your repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up Python (use your desired version)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies (including pytest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run pytest and generate a JUnit XML report
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q --junitxml=report.xml

      # Post the test results to the PR comment
      - name: Post Test Results to PR
        uses: n-ryu/test-reporter@v0.0.2
        with:
          name: Test Results  # Optional: Name of the report section
          path: report.xml   # Path to your JUnit XML report
          reporter: java-junit  # Use the java-junit reporter format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
