name: Continuous Integration

on: 
- push

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install pytest

      - name: test
        run: python -m pytest -v
