name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'testingfolder/test/**'
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: testingfolder/test
      - name: AI Code Review Action
        uses: masroorposh10/codepilotai@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_ENDPOINT: ${{secrets.AZURE_OPENAI_API_ENDPOINT}}
          AZURE_OPENAI_API_MODEL: "gpt-4-v0613"
