name: AI Code Reviewer

on:
    pull_request


jobs:
- job: CodeReview
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: OpenAICodeReviewTask@1
    inputs:
      api_key: ${{secrets.OPENAI_API_KEY}}
      ai_model: 'gpt-3.5-turbo'
      bugs: true
      performance: true
      best_practices: true
      file_extensions: 'js,ts,css,html'
      file_excludes: 'file1.js,file2.py,secret.txt'
      additional_prompts: 'Fix variable naming, Ensure consistent indentation, Review error handling approach'`

