name: CodePilotAI
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'sources/segx/**'

permissions: write-all

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: api/**
      - name: AI Code Review Action
        uses: masroorposh10/codepilotai@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_ENDPOINT: ${{secrets.AZURE_OPENAI_API_ENDPOINT}}
          AZURE_OPENAI_API_MODEL: "gpt-4-turbo-v0613"
