name: CodePilotAI
on:
  pull_request:
    types:
      - opened
      - ready_for_review
    paths:
      - 'sources/segx/**'

permissions: write-all

jobs:
  code_review:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: masroorposh10/codepilotai@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_ENDPOINT: ${{secrets.AZURE_OPENAI_API_ENDPOINT}}
          AZURE_OPENAI_API_MODEL: "gpt-4-v0613"
          exclude: "yarn.lock,dist/**"