name: "Pull Request Commenter"

on:
  pull_request:
    types: [ labeled ]

jobs:
  breaking-changes:
    if: ${{ github.event.label.name == 'BREAKING CHANGES' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |  
          const message = `
            :fire: It looks like this PR contains **BREAKING CHANGES** to API docs, HTTP Clients or contracts.
            
            Please ensure that you have:
            - Planned these changes with all affected parties ahead of time.
            - Reviewed these changes with the front-end team.
          `

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          })