name: Format

on: push

jobs:

  format-code:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Format code with black
        run: |
          black .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format code
          commit_options: '--no-verify --signoff'
          commit_user_name: 'GitHub Actions'
          commit_user_email: 'actions@github.com'